<?php

namespace DOEBELING\BuHaJournal;


/**
 * Class buchungsElementKontoauszug
 *
 * Stell Buchungsdaten aus einem Kontoauszug bereit
 * Stellt statische Methode zum Laden aller Kontoauszüge aus einem Ordner bereit
 *
 * @package   DOEBELING\BuHaJournal\buchungen\buchung
 * @author    Andreas Döbeling <opensource@doebeling.de>
 * @copyright DÖBELING Web&IT
 * @link      https://github.com/ADoebeling/
 * @link      https://www.Doebeling.de
 * @license   CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0/>
 *
 */
class kontoauszug extends buchungsElement
{
    /* RAW
                    [von] => Sparkasse
                    [file] => ../2020/KA - Kontoauszug//Kontoauszugcsv
                    [id] => 1234
                    [datum] => 01.11.2020
                    [an] => Provider
                    [text] => Rechung
                    [betrag] => -3,95
     */

    public static function load(array $input): journal
    {
        if (!is_array($input))
            throw new exception("Load erwartet ein Array");
        $input['csvFelder'] = ['BuchungID' => 'id', 'Wertstellung' => 'datum', 'Kontoname' => 'von', 'Empfänger/Auftraggeber' => 'an', 'Verwendungszweck' => 'text', 'Betrag' => 'betrag'];
        $input['class'] = self::class;
        return parent::load($input);
    }

    protected function validateRaw()
    {
        return parent::validateRaw(); // TODO: Change the autogenerated stub
    }

    protected function parseRawToNr()
    {
        $this->nr = isset($this->raw->id) ? $this->raw->id :'';
        parent::parseRawToNr(); // TODO: Change the autogenerated stub
    }

    /**
     * Methode parseRawToMd
     *
     * @return buchungsElement
     * @example
     * | | Wertstellung: | 01.02.3004 | kontoauszug.csv |
     * | | Kontobewegung | $bankVon *AN*\n$bankAn | kontoauszug.csv |
     * | | Überweisungsbetrag | `1.234,56 €` | kontoauszug.csv |
     * | | Verwendungszweck | lskjdflksjfl dsjfs | kontoauszug.csv |
     * | | Überweisungsvermerk | Testbuchung | kontoauszug.csv |
     */
    protected function parseRawToMd()
    {
        $row = new mdTableRow();

        $an = empty($this->raw->an) ? 'Unbekannt' : $this->raw->an;
        $von = empty($this->raw->von) ? 'Unbekannt' : $this->raw->von;

        $row->setTitle("Überweisung");
        $row->setText("$von *an*<br>$an");
        $row->setLink("{$this->raw->file}");
        $this->mdTable->add($row);
        return parent::parseRawToMd();
    }
}