<?php

namespace DOEBELING\BuHaJournal;

/**
 * Class pdf
 *
 * Stell Buchungsdaten aus abgelegten PDFs bereit
 *
 * @package   DOEBELING\BuHaJournal\buchungen\buchung
 * @author    Andreas Döbeling <opensource@doebeling.de>
 * @copyright DÖBELING Web&IT
 * @link      https://github.com/ADoebeling/
 * @link      https://www.Doebeling.de
 * @license   CC BY-SA 4.0 <https://creativecommons.org/licenses/by-sa/4.0/>
 *
 */
class pdf extends buchungsElement
{
    public static function load(array $input): journal
    {
        if (!is_array($input))
            throw new exception("Load erwartet ein Array");
        $input['class'] = self::class;
        return parent::load($input);
    }

    protected function parseRawToNr()
    {
        $this->nr = self::getBuchungsNrFromString($this->raw->file);
        parent::parseRawToNr(); // TODO: Change the autogenerated stub
    }

    protected function parseRawToMd()
    {
        $row = new mdTableRow();
        $row->setTitle("Beleg");
        $row->setText("{$this->raw->fileName}");
        //$row->setLink("{$this->raw->fileName}");
        $this->mdTable->add($row);
        return parent::parseRawToMd();
    }

}